### ISSUE TITLE
Receive/Send screen: Long assets names in currency selection should be reduced

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#101]
Long assets names in currency selection should be reduced like on Mobile Wallet
WEB
![image](https://user-images.githubusercontent.com/44496108/137450836-478d30c8-7742-41b9-9e2f-d445b4310041.png)
Mobile
![image](https://user-images.githubusercontent.com/44496108/137450948-e962a230-02f9-4356-ad8e-2bf0c90f499e.png)

**Comment by kovaletskaterina** [comment]
checked
