### ISSUE TITLE
Receive/Send screen: Long assets names on Amount field should be reduced

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#102]
Long assets names on Amount field should be reduced like on Mobile Wallet
WEB
![image](https://user-images.githubusercontent.com/44496108/137451125-f0f0d2b7-ca41-4515-9f25-2ced61422c46.png)
![image](https://user-images.githubusercontent.com/44496108/137451080-43f14ef6-2618-4931-b8e4-b40331461215.png)
Mobile
![image](https://user-images.githubusercontent.com/44496108/137451279-75e0bbeb-f627-4c11-96b3-85a1de0a47a8.png)

**Comment by kovaletskaterina** [comment]
checked
