### ISSUE TITLE
Main screen: Long assets names on assets' plates should be reduced

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#103]
Long assets names on assets' plates should be reduced like on Mobile Wallet
WEB
![image](https://user-images.githubusercontent.com/44496108/137453883-7c7dd639-b908-4dc8-844c-ad3a7d6b32bf.png)
Mobile
![image](https://user-images.githubusercontent.com/44496108/137453935-8ced6365-f75b-49cc-ab65-1a821782a273.png)

**Comment by kovaletskaterina** [comment]
Checked
