### ISSUE TITLE
Web apps: closing popups

### ISSUE THREAD

**Issue by chapati** [BeamMW/web-wallet#11]
1) Open faucet & allow connection
2) Try to make deposit / withdraw. Confirmation screen opens. Do not confirm, just leave this screen opened
3) Close faucet 
Result: confirmation screen stays opened
4) Open faucet again
Result: connection request never appears
5) 1-2 then reload
Result: connection request never appears

Fix: When closing / reloading application need to close all popups associated with this app

**Comment by Sergei-Beam** [comment]
checked
