### ISSUE TITLE
[Send screen] USD value should be hidden if a warning message was shown

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#110]
![image](https://user-images.githubusercontent.com/44496108/137725529-52c90957-77ef-4afa-a124-78aec3786e9e.png)

**Comment by Sergei-Beam** [comment]
outdated

**Comment by Sergei-Beam** [comment]
reproduced on the blank wallet ( created from scratch)
![image](https://user-images.githubusercontent.com/44496108/146250715-0cbfdb67-a320-4703-b0e3-3c10adee3498.png)

**Comment by kovaletskaterina** [comment]
Checked
