### ISSUE TITLE
[Send screen] Wrong warning message for simply SBBS address

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#111]
![image](https://user-images.githubusercontent.com/44496108/137726826-6f59c70b-e74e-4e0b-b9af-a8698e212410.png)

**Comment by Sergei-Beam** [comment]
relates to https://github.com/BeamMW/web-wallet/issues/112

**Comment by kovaletskaterina** [comment]
Wrong warning message for the:
1. Regular address includes both online and offline addresses 
![image](https://user-images.githubusercontent.com/83376495/147080216-a8b36273-ea5a-4714-aad4-971d75e50542.png)
Should be written: **Online address** (for the online transaction type) /**Offline address: 1 transaction left. Ask receiver
to come online to support more offline transactions.** (for the offline transaction type).

9DfkirZYqjTSuHBGYKxb3ifi6KFfD8c8PBw3oadvjf2QngakcpzrAvFjRD9avoaNZcTfwpVjKnPctMF3P1pjZ5tEjBywVDfmMLQKw12cT2j5Q9TdBzhEcCiGXbtZuXeVw9AXkD6atEqvZvJxJnVD22ChsEqKwKHTx4pk4B2pxKPREuuhTg1Ga2iQ9vNFuZ73Ff9Jv35d2nraxLYVp4jVAU6UQU5Jqj4mzdCTqBLkk3sNE8QoiZJYfczay6miZ1dmSachV6pSAk5CnMDsueUpKFL8J8c2qR4e1SZJnZD3EAxYFy2C289Lo61Jv7ATLSuswKUYwFpGynFCq6TvVPBz51Nx3anCwPDKbFqZ2Axyat1i2SoPFEMp2NzuzsoRZ52VkfjwjqhUfv2FHaAJLR6ZkUZZP4yHWC3Vv7m9w9jwX2AMKbnMxQv64u4bT2x9BiYdnXvcJxh9K82aePiYEz

2. Online (SBBS) address
![image](https://user-images.githubusercontent.com/83376495/147080275-e7104d2e-9f1c-4da4-b40c-0142cd9e3621.png)
Should be written: **Online address**.

26c3b4b34b996a6ba6cd4451fcd92a2acc7ebdbd61443e36c6f1054081cb88cb18e

3. Public offline address
![image](https://user-images.githubusercontent.com/83376495/147080463-2d1e980d-b569-471e-a0c5-a498c0055eb7.png)
Should be written: **Public offline address**.

2PK8JoXNaa43UkCvy1MJ2t9W8wkxCP9Qxqij4tZPHzkQHAAkEUwi5yVhew9mNvuTcbvAxGFmprf1Jd3wBNq1kfcEmkzzT1RGTMfsj5NwZvo2fPL1uyvzKiZpmq7xywa7qcKnsn1MdmX1ZoM4pPAWBZZDeknJwW4q4Gh5Vh1eZYRW8rHdPB3bspLzRDtPgd7qso2ekzRothJaZi5pcTt6dDxePQpmH37eUkknqAgGmBgk69ELAeAJkGjrEnypdvLxLMGkFpVEkARv2Xw3dXqmuCYXmbh4isKFxGJN2

**Comment by kovaletskaterina** [comment]
Checked
