### ISSUE TITLE
Need to prepare new designs for Web wallet promos on store

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#114]
These is the old promos but needs to prepare new promos
![image](https://user-images.githubusercontent.com/44496108/137907847-4e2583bc-0277-4ae3-9f77-a1e108232145.png)

**Comment by dariatarakanova** [comment]
[2021.zip](https://github.com/BeamMW/web-wallet/files/7388762/2021.zip)

 @Sergei-Beam here are screenshots and promo-banners

**Comment by Sergei-Beam** [comment]
updated on store
