### ISSUE TITLE
Make the errors from fronted part readable

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#119]
![image](https://user-images.githubusercontent.com/44496108/138090285-6773ce74-c4b6-4c12-bd6a-7c1e4497eb84.png)

**Comment by razoorka** [comment]
it is not possible to change the logic of displaying errors, but I have added an error screen
<img width="522" alt="Screenshot 2022-03-12 at 15 34 57" src="https://user-images.githubusercontent.com/5682452/158020028-68acd21f-e602-4f87-b3d8-d8ebe1512410.png">
.

**Comment by Sergei-Beam** [comment]
checked
