### ISSUE TITLE
Add the placeholder for syncing even if user close and reopen extension

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#120]
We need to show the placeholder for syncing even if the user close and reopen the extension
Currently opens the wallet with 0 balance while sync is not 100%
![image](https://user-images.githubusercontent.com/44496108/138091288-f2a6beab-b027-4865-8668-e260067fde3c.png)
![image](https://user-images.githubusercontent.com/44496108/138091319-071cb24c-d4f9-4d75-957b-1f250a73b890.png)

**Comment by kovaletskaterina** [comment]
Checked
