### ISSUE TITLE
There is no space between balance and USD value of the same currency

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#123]
Need to add the space between balance and USD value of the same currency.
![image](https://user-images.githubusercontent.com/83376495/139273329-984bb6ae-b933-4504-ba62-84aba3e03656.png)

**UPD:** 
Decided to add rounding on the main screen
And show full amount when user open asset details screen

**Comment by Sergei-Beam** [comment]
@kovaletskaterina please recheck
