### ISSUE TITLE
Add Lock button - Small view

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/web-wallet#126]
1. Add menu button in the header https://zpl.io/an8Jezr 
<img width="295" alt="Screenshot at Nov 16 23-39-22" src="https://user-images.githubusercontent.com/7249484/142027798-f32589c9-a9cc-4ec2-a724-d15653e80273.png">

2. Menu should have 2 buttons: Lock wallet and Full view https://zpl.io/VD301ge
<img width="297" alt="Screenshot at Nov 16 23-39-34" src="https://user-images.githubusercontent.com/7249484/142027814-4e5d2482-9bb1-4e44-a725-6085f33ee686.png">
(inactive icon for the Full view is here https://zpl.io/V0OBprR)

3. After user locks the wallet, show Enter password screen https://zpl.io/agBO6N0

**Comment by Sergei-Beam** [comment]
need to increase the click area of the menu icon
![image](https://user-images.githubusercontent.com/44496108/149775402-9c580572-fad4-412b-9fb4-de26f6b7c611.png)

**Comment by Sergei-Beam** [comment]
checked
