### ISSUE TITLE
The highlighting is still shown after cleaning up the row on the verification screen

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#137]
After entering and deleting the words highlighting the incorrectly entered word still remains
**Steps:**
- run the wallet
- Click create a new wallet
- click the complete verification button
- enter wrong worlds
- clean up the entered worlds
**Expected**: The highlighting is disappeared
**Actual**: The highlighting is still shown after cleaning up the row on the verification screen
![image](https://user-images.githubusercontent.com/44496108/145849104-86b9498e-90e0-4633-85e7-e49334042d57.png)

**Comment by kovaletskaterina** [comment]
Checked
