### ISSUE TITLE
[Create wallet] Seed phrase should be updated when the user returns back from the validation screen

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#138]
Seed phrase should be updated when the user returns back from the validation screen
![2A75D2F2-D1D3-4750-81AA-586540A7C201](https://user-images.githubusercontent.com/44496108/145868950-d66b3c9e-30f7-4130-9de6-e4a9fcc5a0ae.GIF)

**Comment by kovaletskaterina** [comment]
Checked
