### ISSUE TITLE
[Create wallet] The order of the wallet creation screens

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#139]
Need to implement the flow of the wallet creation screens

1. create/restore screen
![image](https://user-images.githubusercontent.com/44496108/145972714-8dfd43f6-b136-46df-99de-17fb318b90d2.png)
2. after clicking create https://zpl.io/VQn6LJA
![image](https://user-images.githubusercontent.com/44496108/145874390-b8ae91d8-add6-4bc2-ac95-17cd76cb4c61.png)
3. after clicking "I understand" https://zpl.io/29EmOkA
![image](https://user-images.githubusercontent.com/44496108/145874472-321a9239-ce3b-4963-bee7-4c844076181f.png)
4. after clicking "complete verification" https://zpl.io/anQwWpn
![image](https://user-images.githubusercontent.com/44496108/145874539-511fddf6-7082-49d1-8f9d-7dc8d72d9352.png)
5. after clicking done
![image](https://user-images.githubusercontent.com/44496108/145874692-d42abeb4-1b2a-485c-81f5-0025718f19eb.png)
6. after clicking back, show pop-up as on mobile
![image](https://user-images.githubusercontent.com/44496108/145874774-12fcd6c1-7deb-4dd0-a083-2bb69b33e7cc.png)
![image](https://user-images.githubusercontent.com/44496108/145875088-cbaebdd7-6dc7-48b7-98fa-fdec64d0e223.png)
7. after clicking generate the screen from point 3 is shown with regenerated seed
8. after entering verification words and clicking next? the password screen appears
![image](https://user-images.githubusercontent.com/44496108/145876184-2cf7a74d-f915-4eed-9924-e168d407e63d.png)
9. after clicking back from password screen, show pop-up
![image](https://user-images.githubusercontent.com/44496108/145876295-7847c0ca-ade7-4756-8727-38cee66c7da1.png)
10. after clicking "return" the screen from point 3 is shown with regenerated seed

**Comment by kovaletskaterina** [comment]
Checked
