### ISSUE TITLE
Web apps: apps txs in txs list

### ISSUE THREAD

**Issue by chapati** [BeamMW/web-wallet#14]
1) Need to implement support of contract transactions/transactions with multiple assets in the tx list. 
2) Since transaction list shows only limited info need to implement extend transaction info screen.

Take a look at desktop for reference if design is not ready yet.

**Comment by chapati** [comment]
To run app:

1) Install web wallet
2) Login
3) Go to the url

This webapp creates mutiple assets transaction http://3.19.141.112:80/app/dao-core-conf/index.html

![dao core confirmation test - multiple assets confirm](https://user-images.githubusercontent.com/12074933/134712085-4f198c0d-bdd5-47b2-9f7b-18a38d05cf22.png)

![dao core confirmation test - multiple assets tx](https://user-images.githubusercontent.com/12074933/134712099-8311b173-4d99-4e07-aa60-e7c701fa9796.png)

![dao core confirmation test - multiple assets tx details](https://user-images.githubusercontent.com/12074933/134712107-4e7efaad-a396-4c86-89bb-2ee0b6e89caf.png)

This webapp creates fee-only transaction http://3.19.141.112:80/app/enefftee-app/index.html

![nftea join confirm - fee only](https://user-images.githubusercontent.com/12074933/134712122-ed30c88b-5b1e-4ff4-a464-2bfc1a9b23c8.png)

![nftea join confirm - fee only tx](https://user-images.githubusercontent.com/12074933/134712139-4596479c-45f0-42b6-bf03-76117c8b3c7b.png)

![nftea join confirm - fee only tx details](https://user-images.githubusercontent.com/12074933/134712152-3d658d2f-a362-4bf3-87d7-55a59b16bc4e.png)

**Comment by chapati** [comment]
Update web assembly to the latest version.
Contract transactions would have the following format now (invoke_data changed)

{
      "comment": "Lock/Unlock and get farmed demoX tokens",
      "create_time": 1632854550,
      "failure_reason": "Failed to register transaction with the blockchain, see node logs for details",
      "fee": 1100000,
      "fee_only": false,
      "income": false,
      "invoke_data": [
        {
          "amounts": [
            {
              "amount": 1000000,
              "asset_id": 0
            },
            {
              "amount": -10000000,
              "asset_id": 5
            }
          ],
          "contract_id": "8cef85a6ed4f2c3ecbbcd0b5b2cf0fd60c3fd863015f38bf725582f26183308c"
        }
      ],
      "receiver": "",
      "sender": "",
      "status": 4,
      "status_string": "failed",
      "txId": "c66867f0087140c4b75fd96d5439629a",
      "tx_type": 12,
      "tx_type_string": "contract"
    }

1) To get full spend/receive you need to sum amounts by asset_id. 
2) Positive value means that user sends this amount
3) Negative value means that user receives this amount
4) fee_only true - no amounts, user pays only fee in BEAM
5) Before displaying amounts to the user do 'if (totalBeamAmount (asset_id 0) < 0) totalBeamAmount += _contractFee). For example Faucet pays user 5 Beam, transaction fee is deduced from beam amount, so we display 5-fee to the user, screenshot is below:

![gnome-shell-screenshot-L4YEA1](https://user-images.githubusercontent.com/12074933/135168279-7fa8577c-cf4b-412e-a66d-a9df657a24f3.png)

**Comment by Sergei-Beam** [comment]
Amount for withdrawing claimed coins is shown incorrectly. We haven't to deduct commission in BEAM from the amount in BEAMX because it is fully different coins
![image](https://user-images.githubusercontent.com/44496108/137807046-3f9930dc-0383-4b0a-896c-37546bb76ad5.png)

![6F1D3CA3-C601-425C-99F4-9D5FC2902431](https://user-images.githubusercontent.com/44496108/137806844-f4d6e9a1-6cc4-4a20-b142-2822dd63d549.GIF)

**Comment by Sergei-Beam** [comment]
Checked
Note: 
Multiple assets from https://github.com/BeamMW/web-wallet/issues/14#issuecomment-926777917
moved to 
https://github.com/BeamMW/web-wallet/issues/113
