### ISSUE TITLE
Small view - Transaction's list: change design

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#144]
1)  Redesign transaction list https://zpl.io/Vk1vPYg
- add coin icon
- place coin value + name text to the icon
- place USD value on the right side
- place status below coin value
![image](https://user-images.githubusercontent.com/47353570/146030371-b70eafa0-e2ea-464c-a900-1eee8bc9dd82.png)

2) Add "Source" item to each transaction (value should be "Wallet" for wallet transactions or name of the Dapp for contract transactions). https://zpl.io/Vk1vPYg
![image](https://user-images.githubusercontent.com/47353570/146030482-db43411a-4866-4f31-ae04-01200996ad48.png)

3) If there are 2 coins - make both icons with full opacity.

4) If there are 3+ coins - make only 1st icon with full opacity and others with 30% opacity, and show only first coin name and ate "+X".

5) Action will be shown in transaction details https://zpl.io/aXyj6Oj
Will be done in separate task https://github.com/BeamMW/web-wallet/issues/146

![image](https://user-images.githubusercontent.com/47353570/146030660-e5a95664-5404-4052-865f-9689aa75c9fb.png)

**Comment by Sergei-Beam** [comment]
1. checked

2. will be added in API v6.3
3. &  4. moved to https://github.com/BeamMW/web-wallet/issues/208
