### ISSUE TITLE
Small view: Transaction details. Changes.

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#146]
1. Wallet transactions with payment proof. Show info into 2 separate tabs https://zpl.io/aXyj6Oj

General info 
- add coin icons to Amount and Transaction fee
- add copy icon to sending address, receiving address, and transaction ID.
- remove text-link "Open in blockchain Explorer" and leave only the green icon. Place it in one line with Kernel ID.
- text under amount "Calculated with the exchange rate at the time of transaction." - if the rate was successfully calculated 
- text under amount "Exchange rate was not available at the time of transaction." - if rate was not available. And do not show USD rate. https://zpl.io/2pgRwRJ
- add source field
- add action field

![image](https://user-images.githubusercontent.com/47353570/146031308-26b4613a-4f1d-48e1-9952-ab7233b4f919.png)

2. Details for maximum anonymity transaction https://zpl.io/V1AjWM5
![image](https://user-images.githubusercontent.com/47353570/146031685-72290900-aec1-4396-8f75-5737df95f606.png)

3. Payment proof. https://zpl.io/29dGpYl
- add copy icon to sender's and receivers wallet signature, and Code.
- for Kernel ID leave only green icon (external link), remove text "Open in blockchain Explorer"

![image](https://user-images.githubusercontent.com/47353570/146031941-ed6503d0-66bf-4171-bc21-569632f04de2.png)

4. Contract transactions (without payment proof) https://zpl.io/anzB5lk
- add Confidential asset ID next to CA amounts and "link" icons that lead to the asset in blockchain explorer (example https://explorer.beam.mw/assets/details/2)
- place comment about exchange rate under Amount title.
- for Kernel ID leave only green icon (external link), remove text "Open in blockchain Explorer"
- add Source
- add Action

![image](https://user-images.githubusercontent.com/47353570/146032173-b47ba696-a367-456b-a851-f1f5fbcad8cd.png)

**Comment by kovaletskaterina** [comment]
The amount of the incoming and outgoing transactions should be coloured depending on the type of transaction (#0bccf7 for incoming and #da68f5 for outgoing transactions).

1) General info
2. Need to add a copy icon to transaction ID;
3. Need to add green hyper-icon (external link) to a blockchain Explorer. Place it in one line with Kernel ID.
4. Need to change the text under amount from "calculated with the exchange rate at the current time" to "Calculated with the exchange rate at the time of transaction." - if the rate was successfully calculated.
5. text under amount "Exchange rate was not available at the time of transaction." - if the rate was not available. And do not show USD rate. https://zpl.io/2pgRwRJ
7. Need to add the action field.

2) Details for maximum anonymity transactions (https://zpl.io/V1AjWM5)
- when the maximum anonymity transaction fails, the transaction info doesn't show;
- need to add the address type on the general info of the maximum anonymity transaction;
- need to change the text under amount from "calculated with the exchange rate at the current time" to "Calculated with the exchange rate at the time of transaction." - if the rate was successfully calculated;
- need to add the action field;
- need to add the comment field;
- need to add the "copy" icon next to the transaction ID;
- add the green hyper-icon (external link) to a blockchain Explorer next to the Kernel ID.

3) Payment proof (https://zpl.io/29dGpYl)
- need to add the copy icon next to sending and receiving addresses;
- add the address type under the receiving address;
- need to change the text under amount from "calculated with the exchange rate at the current time" to "Calculated with the exchange rate at the time of transaction." - if the rate was successfully calculated;
- need to add the green icon (external link) to a blockchain Explorer next to the Kernel ID;
- need to add the "Code" and the copy icon next to it;

4) Contract transactions (without payment proof) https://zpl.io/anzB5lk
- the “Transaction info” screen of the outgoing transactions to beamx Dao and faucet is blank. Add the information according to the design.

- add Confidential asset ID next to CA amounts and "link" icons that lead to the asset in blockchain explorer (example https://explorer.beam.mw/assets/details/2);
- place a comment about exchange rate under Amount title;
- for Kernel ID leave only green icon (external link), remove the text "Open in blockchain Explorer";
- add Source;
- add Action;

- the subtitle “General” of the transaction info screen should be hidden.
- need to change the text under amount from "calculated with the exchange rate at the current time" to "Calculated with the exchange rate at the time of transaction." - if the rate was successfully calculated;
- need to add the action field
- need to add the copy icon next to the transaction id;
- need to add the green icon (external link) to a blockchain Explorer next to the Kernel ID;

- the transaction info screen for failed public offline and failed maximum anonymity transactions is blank.

**Comment by razoorka** [comment]
1. General info
   4. Rates are hidden.
    5. Rates are hidden.
    6. We do not have this field in BE response.

**Comment by razoorka** [comment]
2. Details for maximum anonymity transactions 
-need to add the action field - we do not have this field in payload
-need to add the comment field - comment will be shown if it is not empty

**Comment by razoorka** [comment]
3. Payment proof 
-need to change the text under amount from "calculated with the exchange rate at the current time" to "Calculated with the exchange rate at the time of transaction." - if the rate was successfully calculated - rates are hidden.
-need to add the "Code" and the copy icon next to it - we do not have this field in BE response.
-add the address type under the receiving address - we do not have this data in response

**Comment by kovaletskaterina** [comment]
_The colour of the amount of the incoming transaction should be #0bccf7. The colour of the outgoing transaction should be #c061e0_
![image](https://user-images.githubusercontent.com/83376495/150797782-355ea365-dcd3-47a8-90b5-14cce06194cf.png)
![image](https://user-images.githubusercontent.com/83376495/150797812-c8a486c4-b1e7-4f45-ac5b-fa1bb05fd3d0.png)
_Please, highlight the amount of the transaction with the colour depending on the type of transaction on the “Transaction info” screen._

3. The green hyper-icon(extra link) to a blockchain Explorer doesn’t work.
![image](https://user-images.githubusercontent.com/83376495/150797917-e3fdd44e-6592-4975-8d65-67d1e6c236a9.png)
4. Contract transactions (without payment proof) https://zpl.io/anzB5lk
- the “Transaction info” screen of the outgoing transactions to beamx Dao and faucet is blank. Add the information according to the design.
- add Confidential asset ID next to CA amounts and "link" icons that lead to the asset in blockchain explorer (example https://explorer.beam.mw/assets/details/2);
- The green hyper-icon(extra link) to a blockchain Explorer doesn’t work.
- add Source;
- the subtitle “General” of the transaction info screen should be hidden.

__The text on the toast bar after copy action (on icon "copy") should be as on the design (https://zpl.io/2GDvWgJ).

![image](https://user-images.githubusercontent.com/83376495/150798554-82ef7477-b8c8-4ff5-b5a2-b63f3539cbcc.png)
![image](https://user-images.githubusercontent.com/83376495/150801971-d5c30753-0e7c-4ed9-9bea-3a37de003c1c.png)
![image](https://user-images.githubusercontent.com/83376495/150822478-ca3aa7e3-6bfd-45f8-a5f2-623c7da8bca7.png)

**Comment by kovaletskaterina** [comment]
- moved to https://github.com/BeamMW/web-wallet/issues/214
- moved to https://github.com/BeamMW/web-wallet/issues/215
- moved to https://github.com/BeamMW/web-wallet/issues/216
