### ISSUE TITLE
Small view: empty wallet screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#148]
Please show icon and text is there are no transactions on the wallet screen.
https://zpl.io/2GwWD4Y

Don't show button "show all" near the transactions (as here https://zpl.io/Vk1vPYg)

![image](https://user-images.githubusercontent.com/47353570/146061753-44e50e0f-af09-47db-99dc-e0d44f687154.png)

**Comment by Sergei-Beam** [comment]
already done
