### ISSUE TITLE
Small view: Assets screen and sorting

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#178]
moved from https://github.com/BeamMW/web-wallet/issues/56
1. Main screen
Need to add:
 **Show All** button for assets 
- If there are only 3 or fewer assets, hide **Show all** icon
- Beam should be placed on top of assets
https://user-images.githubusercontent.com/7249484/116806769-c4640a00-ab61-11eb-8d94-6811a22071e4.png

2. **Assets screen** https://zpl.io/bl3EnNk
Assets screen is opening via clicking on the "Show all" icon near the assets
After opening by default all assets are sorted by "Recently used"

**Sorting** https://zpl.io/bl3EnNk
Need to add sorting icon which calls after clicking the sorting list
All sorting actions should be added from the list above

**Comment by razoorka** [comment]
The screen was done without sorting cause I don't understand how the sort should work and what field it should be based on.

**Comment by kovaletskaterina** [comment]
Checked

- Sorting was moved to the https://github.com/BeamMW/web-wallet/issues/254
