### ISSUE TITLE
Restore from mobile recovery file

### ISSUE THREAD

**Issue by anatolse** [BeamMW/web-wallet#195]
The wallet has the ability to recover from file. It is faster than restoring by mobile node protocol. Please, add this feature to web wallet.
WASM client already has this functionality.
https://github.com/BeamMW/beam/wiki/WASM-wallet-client#importrecovery

Here are URLs where web wallet can download recovery files for different kinds of the BEAM network
https://mobile-restore.beam.mw/testnet/testnet_recovery.bin
https://mobile-restore.beam.mw/mainnet/mainnet_recovery.bin
https://mobile-restore.beam.mw/masternet/masternet_recovery.bin

**Comment by Sergei-Beam** [comment]
checked on the master branch

need to check on testnet and mainnet after build will be ready

**Comment by Sergei-Beam** [comment]
checked
