### ISSUE TITLE
[Send screen]: add the "address details" button and screen

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#199]
The "address details" button and screen should be added for all the types of addresses, for example:
1. regular address https://zpl.io/2EGmRP8
![image](https://user-images.githubusercontent.com/83376495/150330144-444df3ce-b86c-49b4-807f-3db8b01ba343.png)
![image](https://user-images.githubusercontent.com/83376495/150155958-85221166-b0e4-47fb-9f8f-d42c96732c19.png)
2. address with maximum anonymity set https://zpl.io/aNvwDKv
![image](https://user-images.githubusercontent.com/83376495/150330005-46d63e6a-d377-42ab-91b4-1f614afa4ca1.png)
![image](https://user-images.githubusercontent.com/83376495/150156058-502c0396-7412-4083-aed5-c53da73586e8.png)

**Comment by Sergei-Beam** [comment]
need to ask @anatolse about how to get sbbs from regular

**Comment by Sergei-Beam** [comment]
> need to ask @anatolse about how to get sbbs from regular

Task for getting SBBS from Regular was created
https://github.com/BeamMW/web-wallet/issues/354

**Comment by kovaletskaterina** [comment]
1. For address details screen of the **regular address (online and offline)** need to change header from “ADDRESS DETAILS” to “REGULAR ADDRESS”.
After generating a regular address need to add the text “Regular address includes both online and offline addresses.” as on the design.
Delete the "address" title from the screen.
![image](https://user-images.githubusercontent.com/83376495/169289472-4c3b9d8b-8d61-44a0-a77f-65605d1598f7.png)
2. For address details screen of the **SBBS address** need to change header from “ADDRESS DETAILS” to “ONLINE ADDRESS”.
Need to change the title from “ADDRESS” to “ONLINE (SBBS) ADDRESS”
Delete the “online address” title from the screen.
![image](https://user-images.githubusercontent.com/83376495/169289537-0bab9059-0d64-44b5-ab0c-64ba72e66bcd.png)
3. For **maximum anonymity address** change the header from “MAX PRIVACY” to “MAXIMUM ANONYMITY”.
Delete the "address" title from the screen.
![image](https://user-images.githubusercontent.com/83376495/169290567-789133bf-fff7-4995-ac53-6e7ead139f70.png)
4. For **public offline address** change the header from “ADDRESS DETAILS” to “PUBLIC OFFLINE”.
Delete the "address" title from the screen.
![image](https://user-images.githubusercontent.com/83376495/169289642-07f45ffb-f23a-4043-acfc-d0741b77e378.png)

**Comment by kovaletskaterina** [comment]
1. For the regular address the text “Regular address includes both online and offline addresses.” as on the design hadn't been added.
![image](https://user-images.githubusercontent.com/83376495/169987008-7f9d2008-9415-4caf-be32-78801aedd96c.png)

**Comment by kovaletskaterina** [comment]
Checked
