### ISSUE TITLE
Add ability to use Beam extension API in Chromium tabs

### ISSUE THREAD

**Issue by anatolse** [BeamMW/web-wallet#2]
1. Draft version is already implemented in https://github.com/BeamMW/web-wallet-angular contact to @iscander01 for details.
2. Check that it works both in separate tabs and in separate browser windows(angular doesn't work in another window)
3. Note that usage of the wallet API should have minimal differences in case if they are launched from Desktop wallet or inside browser app

**Comment by Sergei-Beam** [comment]
checked
