### ISSUE TITLE
[Receive screen]: add the "address details" button and screen

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#200]
The "address details" button and screen should be added for all the types of addresses, for example:
1. regular address
https://zpl.io/VDQpZWW
![image](https://user-images.githubusercontent.com/83376495/150332789-771ba548-6805-4974-83a7-7679c1ab25c1.png)
https://zpl.io/aXyoEOP
![image](https://user-images.githubusercontent.com/83376495/150332919-e9aa5975-3f22-4463-bc38-94d788928b96.png)
2. address with maximum anonymity set
https://zpl.io/VDQpZWW
![image](https://user-images.githubusercontent.com/83376495/150333037-6a5011ff-ebf1-461e-958e-11b38c4a1ea9.png)
https://zpl.io/aBPl6Qq
![image](https://user-images.githubusercontent.com/83376495/150333150-a460b5a4-8040-4f12-9253-abe1a6b2c301.png)

**Comment by Sergei-Beam** [comment]
> need to ask @anatolse about how to get sbbs from regular

Task for getting SBBS from Regular was created
https://github.com/BeamMW/web-wallet/issues/354

**Comment by kovaletskaterina** [comment]
1. For address details screen of a **regular (online and offline) and SBBS addresses** need to change header from “ADDRESS DETAILS” to “REGULAR ADDRESS”.
After generating a regular address need to add the text “Regular address includes both online and offline addresses.” as on the design.
Add the Online (SBBS) Address to the “REGULAR ADDRESS” details screen.
![image](https://user-images.githubusercontent.com/83376495/169290902-dd1ba7a6-5f92-4adc-9924-11fb3717db7e.png)
2. For the **maximum anonymity address details** change the header from “MAX ANONYMITY” to “MAXIMUM ANONYMITY”.
Delete the "address" title from the screen.
![image](https://user-images.githubusercontent.com/83376495/169290778-7bcccc18-2900-4b75-8606-d02ecf322106.png)

**Comment by kovaletskaterina** [comment]
Checked
