### ISSUE TITLE
Small view: Receive and Send screen: currency selection

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#21]
1) Please add icons to assets.

2) Mail rules:
- BEAM should be always first in the dropdown list.
- Other assets in order: let's use first.
- if only BEAM - no need dropdowns and arrow
- scroll can be added if needed. no need to make dropdown list londer. 4 visible coins per time - is ok.

When we have more assets in the wallet, we will redesign the selection.

3) Send screen

3.1) Open coin's list https://zpl.io/Vq41gEZ
![image](https://user-images.githubusercontent.com/47353570/131676681-14b28140-03f3-4731-9a18-fa3f51392cf9.png)

3.2) Closed coin's list https://zpl.io/bAwOyEn
![image](https://user-images.githubusercontent.com/47353570/131676717-4bf4dd48-be96-4e3d-88be-95a756af0a03.png)

4) Receive screen

4.1) Open coin's list https://zpl.io/25mN8w8
![image](https://user-images.githubusercontent.com/47353570/131676816-cdd85024-920f-4977-8f3c-b1310431afa2.png)

4.2) Closed coin's list https://zpl.io/VDQpZWW
![image](https://user-images.githubusercontent.com/47353570/131676914-82a1d7fe-4088-4b2f-ae76-354ab0f6a3c4.png)

**Comment by Sergei-Beam** [comment]
Need to change Opened/Closed coin's list arrows according to design points 3.2 and 4.2 from description
![image](https://user-images.githubusercontent.com/44496108/137449304-0b14bca1-78f5-4bcf-a0b7-510f0e1adaaf.png)![image](https://user-images.githubusercontent.com/44496108/137449704-e06223a1-8ccf-4d3a-81c4-d414b5a125e0.png)

**Comment by Sergei-Beam** [comment]
checked
