### ISSUE TITLE
[TX info screen] Add Confidential asset ID

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#216]
For the contract transactions (without payment proof) add Confidential asset ID next to CA amounts and "link" icons that lead to the asset in blockchain explorer (example: https://explorer.beam.mw/assets/details/2) https://zpl.io/anzB5lk.
![image](https://user-images.githubusercontent.com/83376495/151345287-9ac08de7-d3b9-40ef-9a2a-e7a940f6bae9.png)

**Comment by Sergei-Beam** [comment]
https://master-net.explorer.beam.mw/assets/details/{id}
https://explorer.beam.mw/assets/details/{id}
https://testnet.explorer.beam.mw/assets/details/{id}

**Comment by Sergei-Beam** [comment]
Checked on master.
Testnet and mainnet will be checked later.

**Comment by Sergei-Beam** [comment]
checked on mainnet
