### ISSUE TITLE
[TX info screen] add the rates for all the types of transactions

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#218]
Need to add the rates:
1. under amount on the general section of the “Transaction info” screen with a comment "Calculated with the exchange rate at the time of the transaction." - if the rate was successfully calculated (for the regular address https://zpl.io/aXyj6Oj);
2. under amount on the general section of the “Transaction info” screen with a comment "Calculated with the exchange rate at the time of the transaction." - if the rate was successfully calculated (for the address with maximum anonymity set https://zpl.io/V1AjWM5);
3. under amount on the “Transaction info” screen for the contract transactions with a comment "Calculated with the exchange rate at the time of the transaction." - if the rate was successfully calculated (https://zpl.io/anzB5lk).
The USD rates under amount shouldn’t be shown if the rate was not available. The text under amount according to design should be "Exchange rate was not available at the time of transaction." https://zpl.io/2pgRwRJ

**Сan't be done and locked till getting API response**
- https://github.com/BeamMW/web-wallet/issues/218

**Comment by chapati** [comment]
Doc are in https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.3 tx_list

**Comment by razoorka** [comment]
`asset_id: 0
comment: ""
confirmations: 7
create_time: 1647277866
fee: 1100000
height: 472567
income: false
kernel: "6e0fa0f1be8a53277a72cab9b52c249745061ec0033b3ed8682b608fd2ab96f1"
receiver: "9DfkirZYqjTSuHBGYKxb3ifi3oGvsjpuoD6h7Cr5mEp7ENoH3UUPnR1eu7Gb499Voa5YbhzCJBwnykdURXDma2RcF62VXtuGLhB1Us7mP1chTALsPajo2ks886bgGZK4ZZC882LvWDeb3VQPx1cTpjzxMKg5u9xi3asbkPGPBbZw96fHnXRDApVHp1CyqCWgVx8ebhFMM13GdcYsgeDRKhixmXYwAkLV2bdmpop6nXKxVnA2k3ZgeTCmkcUSJ6o9DTDPQxgDBDjssxNRtEf57myNWF4fAHVVkxG1JTo2LqZv85sj28S4p9drwEKU5XbMaaP4hEAvibAJio7gjF63XwJtHQdoaJYKVp7peyfiMW9piu9mTHoZDTtnDbuQ16jgxukn6WSfCof3m81UhAiBMJHXqXFjQg3KPGUBLSxa3i4axmwGUyhqCTf1S4gHUiXNYVr22xWiHwLaoRrn6K"
receiver_identity: "d30b7f7d5446e0de226acf74c9d94234fb97fddaa41ae1de5756d04ad17df9cf"
sender: "1b0aeed5aacaf1f05b0682ff1cc25b3abc650ac9539edcfdcaa875da03feec18c0c"
sender_identity: "b60af1393f1f5eee353c88c6a72b858d34ca37fa5e72413a1a9d0e2f3493a3fd"
status: 3
status_string: "sent offline to own address"
txId: "edcacfb882e54b8798ddbf47b83c1816"
tx_type: 7
tx_type_string: "lelantus mw push"
value: 1000000000`

tx detail response 
"beam-wasm-client-masternet": "6.3.12588",

**Comment by Sergei-Beam** [comment]
![image](https://user-images.githubusercontent.com/44496108/159309612-93fd6398-f729-40de-8fd9-dec65b3ebcca.png)
@razoorka Please add some changes here:
- add left padding for text under Asset ammount
- make text style according to the design (color, opacity etc. )https://zpl.io/V1AjWM5
`
.-USD-alculate {
  width: 303px;
  height: 30px;
  margin: 2px 0 0 10px;
  opacity: 0.5;
  font-family: ProximaNova;
  font-size: 12px;
  font-weight: normal;
  font-stretch: normal;
  font-style: normal;
  line-height: normal;
  letter-spacing: normal;
  color: #fff;
}
`

**Comment by kovaletskaterina** [comment]
- Add the space between the rate and the comment 

![image](https://user-images.githubusercontent.com/83376495/160592606-4ef1d759-ec3c-415f-a802-484c5714310b.png)

- Need to add the text under amount "exchange rate was not available at the time of transaction." - if the rate was not available. And do not show USD rate. https://zpl.io/2pgRwRJ

![image](https://user-images.githubusercontent.com/83376495/160592303-4f50b429-c9a6-496b-bccb-0338d7c0be94.png)

**Comment by kovaletskaterina** [comment]
Checked
