### ISSUE TITLE
Small view: send screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#22]
1) Please replace elements in header according to updated design https://zpl.io/Vk4z3YZ
![image](https://user-images.githubusercontent.com/47353570/111681563-0c3a0680-882c-11eb-9d48-0a953f22a43c.png)

2) Empty screen https://zpl.io/254vwMr
- make all title in white color
- make sub-titler in grey color

![image](https://user-images.githubusercontent.com/47353570/131528853-269131cd-ed32-4544-937f-5435ac7504c3.png)

3) If receiver sends to sender regular address (maximum anonymity set OFF) - sender can choose the transaction type: Online or Offline https://zpl.io/Vxqm6R3
- add comment "Online address" under address field
- add comment "The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards." under "Next" button

![image](https://user-images.githubusercontent.com/47353570/131528971-f801df62-a382-47b7-80ec-be91477aa047.png)

4) Offline transaction https://zpl.io/ad35PWp
add a comment below address "Offline address: 1 transaction left. Ask receiver to come online to support more offline transactions." (there is 1 offline tx always)
add comment "Make sure the address is correct as offline transactions cannot be canceled." under next button

![image](https://user-images.githubusercontent.com/47353570/131531693-e8ea7da5-eeb5-49a0-b575-ed91e2fb9c65.png)

5) Only online transaction (if user copy only SBBS address from receive screen) https://zpl.io/2v8M6Kj
- No need block "Transaction Type"
![image](https://user-images.githubusercontent.com/47353570/131531841-97bb1d5f-8bb4-4a83-bdba-90322148575a.png)

6) If receiver sends to sender Maximum anonymity set address https://zpl.io/boE1MKm
- no need for Transaction tyle block
- add comment "Guarantees maximum anonymity set of up to 64K." under the address field
- add comment "Transaction can last at most 72 hours." or "Transaction can last indefinitely." under Next button
![image](https://user-images.githubusercontent.com/47353570/131532004-72c00d54-7b98-4d64-b756-ddca7cca8c0e.png)

7) Confirmation screen https://zpl.io/Vx3e1ow
- no need comment about recipient must get online...
![image](https://user-images.githubusercontent.com/47353570/131532103-b18978f7-00ae-4538-b5eb-d92aaf7b0c34.png)

8) Regular address details https://zpl.io/2EGmRP8
![image](https://user-images.githubusercontent.com/47353570/131532188-b51c5768-05dc-4146-a66d-e4f165cc2acc.png)

9) Address details with maximum anonymity set https://zpl.io/aNvwDKv
![image](https://user-images.githubusercontent.com/47353570/131532205-33e29f27-ce75-4f8f-88c5-2f5ee5f861d1.png)

10) When focus on address filed - add "x" icon that removes address at all. https://zpl.io/25mEAAJ
![image](https://user-images.githubusercontent.com/47353570/131532817-4c3b02f6-b457-455d-8d19-9056946e4b99.png)

**Comment by kovaletskaterina** [comment]
Send screen:
1. Need to replace the elements of the header according to the design https://zpl.io/Vk4z3YZ
3. Under the address field comment _"Regular address"_ should be changed to _"Online address_".
4. Comment under the address field should be changed to _"Offline address: 1 transaction left. Ask receiver to come online to support more offline transactions."_
5. Address type should be changed from _"regular"_ to _"online"_.
7. The comment "The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards." shouldn't be shown on the confirmation screen.

- According to the design, the button should be _"⬆️send"_ instead of _"➡️next"_.

8. The "address details" button and screen for the regular address should be added.
9. The "address details" button and screen for the address details with maximum anonymity set should be added.
10. The "x" button on the address field should be added.

**Comment by razoorka** [comment]
According to @beam-mw address, details should be moved to the next release.

**Comment by kovaletskaterina** [comment]
On the send confirmation screen:
1. the transaction type for the regular address should be changed from "online" to "regular";
![image](https://user-images.githubusercontent.com/83376495/150338346-44951c45-4ae6-48ca-b949-2e1ab24cde51.png)
2. the comment "The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards." should be hidden.
![image](https://user-images.githubusercontent.com/83376495/150338386-12862287-2c42-4a2c-98a9-a592bdfc1d46.png)
3. The "x" icon that removes the address at all should be as on the design https://zpl.io/25mEAAJ.
![image](https://user-images.githubusercontent.com/83376495/150529855-dcb0d879-3026-4ba0-960a-e33b6769ba3e.png)

**Comment by kovaletskaterina** [comment]
Checked
