### ISSUE TITLE
[TX info screen] add the Source field and the Action field

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#220]
**Can’t be done and locked till getting API response** 
- https://github.com/BeamMW/beam/issues/1864

On the transaction info screen for all the types of transactions (for example, contract transactions https://zpl.io/anzB5lk; regular transactions https://zpl.io/aXyj6Oj; maximum anonymity transactions https://zpl.io/V1AjWM5) the Source field and the Action field should be added. 
![image](https://user-images.githubusercontent.com/83376495/151360569-079b6ccf-0efa-4827-bdd0-edd2910d3213.png)

**Comment by Sergei-Beam** [comment]
We already have the source in 6.3 API
For the Action field, the task was created 
- https://github.com/BeamMW/beam/issues/1864

**Comment by kovaletskaterina** [comment]
The Source field is checked. For the Action field a new task is created.
- https://github.com/BeamMW/web-wallet/issues/231
