### ISSUE TITLE
[TX info screen] add the payment proof “Code”

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#221]
On the Payment proof section in the "Transaction info" screen add the payment proof "Code" with a copy icon (https://zpl.io/29dGpYl)
![image](https://user-images.githubusercontent.com/83376495/151360680-0906d3e0-0552-42b1-8cce-ec906b2c873e.png)

**Comment by Sergei-Beam** [comment]
We already have it in response _ExportPaymentProof_ which required only tx_id.
Please get it from it and add it to UI
![image](https://user-images.githubusercontent.com/44496108/151526427-784db886-69e0-48bb-a307-a0293c0f5b13.png)

**Comment by kovaletskaterina** [comment]
Checked
