### ISSUE TITLE
Small view: transaction details screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#23]
Full view: https://github.com/BeamMW/web-wallet/issues/209

**1. Wallet transactions with payment proof. Show info into 2 separate tabs.**

1.1. General info https://zpl.io/aXyj6Oj

- add coin icons to Amount and Fee
- add copy icon to sending address, receiving address, and transaction ID.
- text under USD amount  "(calculated with the exchange rate at the time of transaction)" - if the rate was successfully calculated https://zpl.io/aXyj6Oj
- text under USD amount  "(exchange rate was not available at the time of transaction)" - if rate was not available. And do not show USD rate https://zpl.io/2pgRwRJ
- remove text-link "Open in blockchain Explorer" and leave only the green icon. Place it in one line with Kernel ID.

![image](https://user-images.githubusercontent.com/47353570/131822582-47b42c40-6778-4bc2-90e1-2f7c6412d79e.png)

![image](https://user-images.githubusercontent.com/47353570/131822661-051e78a8-ed4c-4034-ad63-1381eca4237d.png)

1.2 Details for maximum anonymity transaction https://zpl.io/V1AjWM5
![image](https://user-images.githubusercontent.com/47353570/131822766-4b720979-a3a8-48ff-9498-14c0e55014ba.png)

1.3. Payment proof. Works only for sending transactions. https://zpl.io/29dGpYl
- add copy icon to sender's and receivers wallet signature and Code.
- text under USD amount  "(calculated with the exchange rate at the time of transaction)" - if the rate was successfully calculated https://zpl.io/aXyj6Oj
- text under USD amount  "(exchange rate was not available at the time of transaction)" - if rate was not available. And do not show USD rate https://zpl.io/2pgRwRJ
- remove text-link "Open in blockchain Explorer" and leave only the green icon. Place it in one line with Kernel ID.

![image](https://user-images.githubusercontent.com/47353570/131822844-5ea24aff-86a8-451a-ad4b-e3ffb130af95.png)

**2. Contract transactions (without payment proof)** https://zpl.io/anzB5lk

- add Confidential asset ID next to CA amounts and "link" icons that lead to the asset in blockchain explorer (example https://explorer.beam.mw/assets/details/2)
- add Dapp name, Application shader, Description (not Comment)
- place a comment about the exchange rate under amounts (title).
- If more than 1 coin - AMOUNTS should be in plural

![image](https://user-images.githubusercontent.com/47353570/131822920-104936db-1f21-427d-8d35-3812ce2dc36b.png)

3. In tx list highlight transactions on hover. Open transaction details through action menu https://zpl.io/bLJqv5m
![image](https://user-images.githubusercontent.com/47353570/131181410-c938dd3c-233d-4292-8a4a-f38a0a61fde2.png)

**Comment by razoorka** [comment]
duplicate https://github.com/BeamMW/web-wallet/issues/146
