### ISSUE TITLE
Wallet stops after clicking the lock wallet button

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#232]
When the user clicks the Lock button we should show the authorization screen but the wallet stops after clicking the lock button instead of proceeding to work in the background.

Steps:
- create/restore wallet
- open wallet
- navigate to three dots on the right corner
- Click lock wallet
Expected: the authorization screen is shown and the wallet proceeding to work in the background.
Actual: after clicking the lock button the wallet stops working
![image](https://user-images.githubusercontent.com/44496108/152942828-b0d00bcc-c156-4261-aedf-5d402e8043ed.png)

**Comment by kovaletskaterina** [comment]
Checked
