### ISSUE TITLE
Small view: Move Settings from option (3 dots) to Burger menu

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#24]
1) Please remove Settings from options (three dots, top right corner) and remove options at all. 
![image](https://user-images.githubusercontent.com/47353570/134919259-77b50014-1622-48b1-b8ad-da7e4bccacc6.png)

2) Place icon "show full view" to the top right corner https://zpl.io/agB6xoD
![image](https://user-images.githubusercontent.com/47353570/134656434-05d8cabb-9c0a-443a-824c-1366ff1e4fab.png)

3) Please add Settings icon to side menu https://zpl.io/agB6xoD
![image](https://user-images.githubusercontent.com/47353570/134656516-6d3c77aa-84de-4f72-a192-d0c802c5a45f.png)

**Comment by Sergei-Beam** [comment]
already done
