### ISSUE TITLE
Receive screen. Add message that mimblewimble addresses are always new because of the privacy

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/web-wallet#25]
Please add a comment under address, only for regular addresses.

Small view: https://zpl.io/aX78Pgl
![image](https://user-images.githubusercontent.com/47353570/134478404-547177fc-0c02-4930-bcc2-6442a50bb2ae.png)

Full view: https://zpl.io/aX785LK
![image](https://user-images.githubusercontent.com/47353570/134479324-737041a2-51cc-4bdc-a3ea-0a250ddb6043.png)

**Comment by kovaletskaterina** [comment]
Checked.
The text "In case you’d like to re-use an earlier created regular address please use the Address Book." will be added after the implementation Address Book.
