### ISSUE TITLE
After click on Send/Receive from Asset's details screen asset should be preselected

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#259]
After click on Send/Receive from Asset's details screen asset should be preselected from coin dropdown
Web
![image](https://user-images.githubusercontent.com/44496108/160094156-e11d50aa-528c-455c-993b-a405487b29b3.png)
![image](https://user-images.githubusercontent.com/44496108/160094172-be9e8367-9315-4ab6-a6eb-03367da991bf.png)
![image](https://user-images.githubusercontent.com/44496108/160094180-95164ef0-b2cf-4eb4-9841-3c1df58cc2f9.png)

Mobile
![8016B535-3358-445C-B7DF-FAF2EB882FA9](https://user-images.githubusercontent.com/44496108/160094753-6d7a6cbe-0fe5-4cb8-8f3b-dbe74c0ee902.GIF)

**Comment by Sergei-Beam** [comment]
Coin isn't preselected if I'm clicking receive button from Asset's details
![7CB8B3C4-99C6-4790-8045-BE98753DA546](https://user-images.githubusercontent.com/44496108/161526102-1819f79d-a82c-4b21-9497-882997ce22e5.GIF)

**Comment by kovaletskaterina** [comment]
Checked
