### ISSUE TITLE
Update Beam logo everywhere in the webwallet

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#26]
**Small view**

1) In header https://zpl.io/agB6xoD
![image](https://user-images.githubusercontent.com/47353570/134569894-402d934c-7837-471b-bcac-fa359847eb4a.png)

Please pay attention that if there is a big logo on the screen (as on create a wallet or login screen) no need to add the small logo in the header.

2) Create wallet (and restore for future versions) https://zpl.io/Vq5pRm7
![image](https://user-images.githubusercontent.com/47353570/134571437-1e90fbbc-78e1-42c5-84b4-ffd2ec974279.png)

3) Login screen  https://zpl.io/agBO6N0
![image](https://user-images.githubusercontent.com/47353570/134570860-6396bd60-fa71-4c34-bd05-4770bd327546.png)

**Full view**

1) In the header https://zpl.io/bey91lz
![image](https://user-images.githubusercontent.com/47353570/134572084-eb544f73-a64d-48bf-a9cf-ef58ecf6cfac.png)

2) Create wallet https://zpl.io/a7xgqKp https://zpl.io/bL0159G
![image](https://user-images.githubusercontent.com/47353570/134573476-701e5444-2584-4622-8d4e-85f6e93634ae.png)

3) Login screen https://zpl.io/bJ0YGAD
![image](https://user-images.githubusercontent.com/47353570/134573564-4fa7cf5a-844b-44c4-be34-0f5b222cd215.png)

**Comment by kovaletskaterina** [comment]
The small view was checked. 
The full view was moved to https://github.com/BeamMW/web-wallet/issues/183
