### ISSUE TITLE
Add rates to the amount field on the send confirmation screen

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#266]
Need to add rates to the amount field on the send confirmation screen
![image](https://user-images.githubusercontent.com/83376495/162164038-becf17f0-67e0-49a4-8d3d-dec1c2739df4.png)

**Comment by razoorka** [comment]
JFYI, at the moment when the transaction was not sent, we only have the BEAM rate. If we need such improvement for all assets, we need an additional BE endpoint to retrieve the asset rate.

**Comment by kovaletskaterina** [comment]
We don't have rate for any asset, that is why we don't need rates for them. Let's add the rates for beam amount.

**Comment by kovaletskaterina** [comment]
Checked
