### ISSUE TITLE
Small view: Header

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#27]
Please replace elements in the header according to the updated design https://zpl.io/Vk4z3YZ
1) logo to the left corner
2) status "online" next to the logo 

![image](https://user-images.githubusercontent.com/47353570/131506738-5b2ee18f-0d57-42cf-a425-8326c1e13832.png)

Current implementation:
![image](https://user-images.githubusercontent.com/47353570/131655750-e1420035-4dae-42d4-b5c6-12dae9c050f8.png)

**Comment by kovaletskaterina** [comment]
Checked
