### ISSUE TITLE
Small view: Rework password screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#28]
1) Empty password fields https://zpl.io/25jKjxn
- replace line input field with box input field
- place the password requirement below the password and it's confirmation.
- button inactive
- make 10% opacity (instead of 5%) on selected field (as on "Password" field)
![image](https://user-images.githubusercontent.com/47353570/131639495-c911e5f4-6352-4544-a271-9b82a4eecd82.png)

2) Password filled, confirmation - error https://zpl.io/bzxGxRM
- make box in red color (oppacity 15%)
- button inactive because of error
- add error text
![image](https://user-images.githubusercontent.com/47353570/131150518-bf2875bf-52a0-456f-9f46-eb3b2ad742f0.png)

3) Password filled and confirmation correct https://zpl.io/beyMPOq
- button active
![image](https://user-images.githubusercontent.com/47353570/131640009-9034788a-9cb2-4a8a-886b-52d0bd698c45.png)

4) Show icon "show/hide password" only on focus field https://zpl.io/bPNrr7L
![image](https://user-images.githubusercontent.com/47353570/131640078-920ae246-406e-46f9-acaa-dd3e284b6de1.png)

Text for all password states here https://zpl.io/b6oK1kq

**Comment by kovaletskaterina** [comment]
1. The title of the password confirmation field should be “Password confirmation”. 
The “eye” button should be shown on the focus field.
The text on the "start using your wallet" button should be started with lowercase letter.
![image](https://user-images.githubusercontent.com/83376495/170979356-256b0b7e-69be-46ac-81d8-f69bf709a2c8.png)
2. The “eye” button should be shown on the focus field.
![image](https://user-images.githubusercontent.com/83376495/170981954-dc205c8b-fa36-44b4-9536-c0e9bfa82031.png)
3. The word “weak” in the “Very weak password” status should be started with a lowercase letter.
![image](https://user-images.githubusercontent.com/83376495/170982185-53a169a1-3e03-4493-ac3b-9fe3d11dc177.png)
Incorrect status for the “Medium strong password”. Change the word “strength” to “strong”.
![image](https://user-images.githubusercontent.com/83376495/170982249-3373ab40-500b-434f-8126-ef1edbe53a68.png)

**Comment by kovaletskaterina** [comment]
The word “password” in the title of the password confirmation field (“Confirm password”) should be started with a lowercase letter.
![image](https://user-images.githubusercontent.com/83376495/172574628-cb1114f1-809f-40be-a975-9cd0750db54c.png)

**Comment by kovaletskaterina** [comment]
Checked
