### ISSUE TITLE
Add link to Beam docs

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/web-wallet#29]
Please add new icon to the side menu that leads to https://documentation.beam.mw/

Full view design: https://zpl.io/2v3eXWJ
Small view design: https://zpl.io/agB6xoD

![image](https://user-images.githubusercontent.com/47353570/134468447-1ad72618-95ad-4330-adb5-8409c5b40a92.png)

![image](https://user-images.githubusercontent.com/47353570/134468423-86e8ca1a-69a2-4875-8032-62b00ce40e39.png)

**Comment by kovaletskaterina** [comment]
Checked
