### ISSUE TITLE
Assets color palette

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#30]
The color palette here: https://zpl.io/V4gl8Zy

For the first 20 assets, you can use these colors.
![image](https://user-images.githubusercontent.com/47353570/122907923-48659180-d35c-11eb-8f85-03746ce6c20a.png)

The color is bound to Asset ID, same as it was implemented on desktop and mobile. Please talk to @chapati for details as he invented the mapping.

**Comment by Sergei-Beam** [comment]
Incorrect colours for assets, all assets should have the same colour throughout the project
![image](https://user-images.githubusercontent.com/44496108/135859454-723aeca4-b1a4-4c32-9a8b-496b782f03eb.png)
![image](https://user-images.githubusercontent.com/44496108/135859516-6e921d26-0a4a-4696-a5d7-a20274daf02c.png)

**Comment by Sergei-Beam** [comment]
the fourth Assets palette has no style
![image](https://user-images.githubusercontent.com/44496108/136456397-fc0db7a7-8085-428a-b86a-ea0b5e8e096a.png)
![image](https://user-images.githubusercontent.com/44496108/136456336-6157dfae-3cd2-47b6-a1b4-edfd724fc6c6.png)

**Comment by iscander01** [comment]
Also fixed incorrect icons

**Comment by Sergei-Beam** [comment]
Looks like gradient is configured differently on the web than on Desktop because some of the colour matched but some looks different
@iscander01 Could you investigate it?
![image](https://user-images.githubusercontent.com/44496108/137689133-6b5ab4d8-91e8-4050-99f1-8f3e6e3fd46b.png)

**Comment by iscander01** [comment]
in desktop asset DEMOX with id = 5 is getting color from broadcaster

**Comment by Sergei-Beam** [comment]
checked
separate tickets for broadcaster were created
https://github.com/BeamMW/web-wallet/issues/107
https://github.com/BeamMW/web-wallet/issues/108
