### ISSUE TITLE
While restoring the other wallet, the list of transactions remains from the previous wallet

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#301]
When you restore any other wallet via "Remove current wallet" button, the list of transactions remains from the previous wallet until you restart the extension. Looks like it stores somehow in browser cache and uploads after restore.
**Steps to reproduce:**
1. Open web wallet.
2. Remember the list of transactions.
3. Tap the menu and go to the settings screen.
4. Press the "Remove current wallet" button.
5. Tap the "next" button on the  "Remove current wallet" pop-up, then enter the password and press "remove".
6. Press the "Restore wallet" button.
7. Tap "I agree" on the restore wallet pop-up.
8. Enter your seed phrase and press "Submit".
9. Enter and confirm your password.
10. Wait until the wallet loads.
11. Check the transaction list after restore the wallet.
**Expected result:** transactions don't remain from the previous wallet.
**Actual result:** transactions remain from the previous wallet.

**Comment by kovaletskaterina** [comment]
Is still reproduced

**Comment by razoorka** [comment]
dolphin;view;cream;plunge;crouch;welcome;bulk;monkey;check;slice;omit;gadget;

**Comment by kovaletskaterina** [comment]
Checked
