### ISSUE TITLE
[Restore] An incorrect wallet balance is restored from downloaded restore file

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/web-wallet#309]
While restoring the same wallet on the desktop application and on the web extension by certain seed phrases, the wallet balance is different.
_Note: during the restore, fast-sync restore file is used by web wallet._ 
![image](https://user-images.githubusercontent.com/83376495/171624176-16676e50-8925-44cb-b01f-6e11b233a561.png)
![image](https://user-images.githubusercontent.com/83376495/171624197-5201f8ac-1cac-481f-801c-cd478f47d2a1.png)

Also, when trying to send the transaction from the web wallet with one of the seed phrase, the transaction fails with the logs:
```
D 2022-06-02.13:24:03.485 [77f37cc061c74baeb3015ba0e1a04467][1] register status 17
I 2022-06-02.13:24:03.509 [77f37cc061c74baeb3015ba0e1a04467][1] Get proof for kernel: 04a17a90931dec6b
E 2022-06-02.13:24:03.568 [77f37cc061c74baeb3015ba0e1a04467] Failed. Failed to register transaction with the blockchain, see node logs for details
I 2022-06-02.13:24:03.585 [77f37cc061c74baeb3015ba0e1a04467] Transaction failed. Rollback...
```
![image](https://user-images.githubusercontent.com/83376495/171624246-1ae3005b-3e75-468e-a7b8-1a32715d353b.png)

**Comment by anatolse** [comment]
for his seed fringe;curtain;few;calm;gasp;stable;oven;buyer;idle;shadow;steak;balcony;
mobile wallet doesn't see this event
I 2022-06-02.15:41:08.847 Shielded output, ID: 5106 Spent, Height=547982

**Comment by Sergei-Beam** [comment]
The problem was solved.
There was an issue on the server side.
