### ISSUE TITLE
Loading wallet indicator small fixes (text)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#31]
Changes:
Remove additional header line, leave only secondary text.
Update text: "Syncing with the blockchain: calculating estimated time"
"Syncing with the blockchain: X mins to completion"
"Syncing with the blockchain: less than a minute to completion"
Important: percents should be displayed only in whole numbers (5%, no 5.5%)

New design
https://zpl.io/ble74Bz
https://zpl.io/2yoYXpJ

![image](https://user-images.githubusercontent.com/7249484/131185705-b3b5e56b-6553-4d03-8ca0-befe7210cb0e.png)
![image](https://user-images.githubusercontent.com/7249484/131185719-7f0bedc5-a597-49c1-80a8-aaf1da346b4d.png)

**Comment by razoorka** [comment]
In the current implementation, we do not have time calculation, but all other stuff seems fine.
