### ISSUE TITLE
[Restore] Incorrect screens order due to back steps

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#313]
When you return from the password screen via clicking the "back" button to the seed phrase screen and then press the "back" button, the wallet returns you to the password screen again.
**Steps to reproduce:**
1. Open the web wallet.
2. Press the "Restore wallet" button.
3. Tap "I agree" button on the "Restore wallet" pop-up.
4. Type in your seed phrase and press the "Submit" button.
5. Fill in your password and press the "back" button. The wallet returns you to the seed phrase screen. Pay attention that the seed phrase words fields are empty.
6. Tap the "back" button.
**Expected result:** The main screen is opened.
**Actual result:** The wallet returns you to the password screen.

**Comment by kovaletskaterina** [comment]
Checked
