### ISSUE TITLE
Small view: Update splash screen with new logo and graphics

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#32]
Full view here https://github.com/BeamMW/web-wallet-angular/issues/244

Please update the logo, text "Confidential DeFi Platform and Cryptocurrency" and background illustration https://zpl.io/2Gwjyk3'
![image](https://user-images.githubusercontent.com/47353570/134477551-52b61e61-84c5-47b0-9eb2-8b2b846493a0.png)

Current implementation
![image](https://user-images.githubusercontent.com/47353570/134477601-5092100a-822a-4103-a61d-7f326aa92934.png)

**Comment by kovaletskaterina** [comment]
Checked
