### ISSUE TITLE
Incorrect sorting while wallet is open

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#39]
If the wallet open during incoming transactions then they placing incorrectly in the transaction list, sorting should be **by created date**
![image](https://user-images.githubusercontent.com/44496108/135857012-95ad8f5f-0e76-43c3-865b-93ed94437059.png)
But after close and reopen the extension the transactions is sorted correctly
![image](https://user-images.githubusercontent.com/44496108/135857059-b12eff26-cc3c-437c-be1b-a77f0d3df225.png)

**Comment by kovaletskaterina** [comment]
Checked
