### ISSUE TITLE
Show popup or move focus to the web wallet extension when application have to get consent from user

### ISSUE THREAD

**Issue by anatolse** [BeamMW/web-wallet#4]
Some actions (sending beams and etc.) require user's consent. When application initiates such an action we need to move user's focus to the wallet extension, and extension should show consent dialog or something similar.
In order to handle this, you have to subscribe to two notifications in WASM wallet client:
```javascript
          walletClient.setApproveSendHandler((request, info, cb)=>{
              console.log("Request: " + request);
              console.log("Info: " + info);
              cb.setApproved(request);
              //cb.setRejected(request);
          }) 
          walletClient.setApproveContractInfoHandler((request, info, amounts, cb)=>{
              console.log("Request: " + request);
              console.log("Info: " + info);
              cb.contractInfoApproved(request);
              //cb.contractInfoRejected(request);
          })
```
The callback allows to approve/reject the `request`, `info` is a JSON with data describing beam transaction

**Comment by Sergei-Beam** [comment]
checked
