### ISSUE TITLE
Send screen: Amount field has a less maximum value that expected

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#46]
Currently, the Amount field on the WEB wallet has a less maximum value than expected.
The desktop wallet has the next maximum value **253999999.99999999** which is controlled using a regular expression
`"^(([1-9][0-9]{0,7})|(1[0-9]{8})|(2[0-4][0-9]{7})|(25[0-3][0-9]{6})|(0))(\\.[0-9]{0,%1}[1-9])?$"`
Need to adapt this field to desktop wallet value
![2CE32C93-ACD9-4760-A0AD-17EBC19E9E3E](https://user-images.githubusercontent.com/44496108/136084982-c2e6bd73-ddac-4a67-ae25-3739e0f59f16.GIF)

**Comment by Sergei-Beam** [comment]
need to stop the input if the user wants to exceed the maximum amount instead of switching to maximum

![364F1859-38C6-43CA-81B7-1DEFA98B548E](https://user-images.githubusercontent.com/44496108/146908239-f01ff1a7-0ec9-425c-8cde-86a7b2d396e7.GIF)

**Comment by kovaletskaterina** [comment]
Checked
