### ISSUE TITLE
Wasm cannot extract information from address

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#49]
When I paste the new regular address( with offline) Or max privacy, I'm catching errors in background logs
![image](https://user-images.githubusercontent.com/44496108/136377716-69ccbb32-8bb6-41a6-9410-4ae1599958a7.png)
![image](https://user-images.githubusercontent.com/44496108/136377727-c1c6bbda-4ea9-460f-a138-819338160a6d.png)

**Comment by anatolse** [comment]
fixed in https://github.com/BeamMW/beam/commit/d4e0b3b316da7de4b9aa4daa2d740316a6ccf17f

**Comment by Sergei-Beam** [comment]
checked
