### ISSUE TITLE
Send/Receive: make the comment field collapsed by default

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#52]
![image](https://user-images.githubusercontent.com/44496108/136457257-984ee5a9-d438-4140-93e3-45f82e57fcef.png)
![image](https://user-images.githubusercontent.com/44496108/136457284-2feeb411-98fd-4ac9-944d-d7280daec1f5.png)

**Comment by beam-mw** [comment]
Remove comment field
