### ISSUE TITLE
Add wallet version into extensions' list

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#54]
Need to show current wallet session on extensions' list 
![image](https://user-images.githubusercontent.com/44496108/136770515-7c9c41d5-47d9-4ecc-962f-be959f141a9d.png)

**Comment by anatolse** [comment]
API already has  method to retrieve library version
https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.1#get_version

Need to add changes which would update manifest.json with the version from beam-wasm-client package

**Comment by Sergei-Beam** [comment]
Except for the extensions' list, we need to add the  wallet version into wallet settings
@5angel Please add it to wallet settings too
![image](https://user-images.githubusercontent.com/44496108/136992992-af71f9f3-13af-4219-abb0-f650da1dc35e.png)

**Comment by Sergei-Beam** [comment]
adding version on wallet settings screen was moved to https://github.com/BeamMW/web-wallet/issues/95
