### ISSUE TITLE
Web-wallet small view: main screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/web-wallet#56]
1. Main screen https://zpl.io/Vk1vPYg
![ww wallet](https://user-images.githubusercontent.com/7249484/116806769-c4640a00-ab61-11eb-8d94-6811a22071e4.png)
If there's only 3 or less assets, hide Show all icon https://zpl.io/bWyP1J1
![image](https://user-images.githubusercontent.com/7249484/130810809-846d4f00-f7a1-49c5-ac5d-db28d4301adc.png)
2. Assets screen + sorting https://zpl.io/bl3EnNk
![ww assets](https://user-images.githubusercontent.com/7249484/116806778-cfb73580-ab61-11eb-9b22-0751c01ebeb7.png)
3. Asset's detail screen https://zpl.io/V1xdLZX
![ww asset confi](https://user-images.githubusercontent.com/7249484/116806794-e493c900-ab61-11eb-8a0c-914ba1c871ca.png)
4. Asset's info and extended balance 
https://zpl.io/ag3dEGZ
https://zpl.io/ad35oM7
![image](https://user-images.githubusercontent.com/7249484/130844070-2e82352f-40c7-470d-960c-e2d1b76cd9c4.png)
![ww assets info](https://user-images.githubusercontent.com/7249484/116806810-05f4b500-ab62-11eb-9082-56f27ef4022b.png)

**Comment by Sergei-Beam** [comment]
1. Main screen
 Need to add:
 **Show All** button for assets 
- If there are only 3 or less assets, hide **Show all** icon
- Beam should be placed on top of assets
https://user-images.githubusercontent.com/7249484/116806769-c4640a00-ab61-11eb-8d94-6811a22071e4.png

Eye icon for hiding ALL balances. 
- By default it is unclicked and all balances are presented
- if an icon is clicked then the icon become strikethrough and ALL amounts in balances and transactions should be hidden
- if the user clicks strikethrough eye again ALL amounts in balances and transactions should be shown

2. moved to https://github.com/BeamMW/web-wallet/issues/178
3. moved to https://github.com/BeamMW/web-wallet/issues/179
4. moved from https://github.com/BeamMW/web-wallet/issues/180

**Comment by Sergei-Beam** [comment]
> 1. Main screen
>    Need to add:
>    **Show All** button for assets
> 
> * If there are only 3 or less assets, hide **Show all** icon
> * Beam should be placed on top of assets
>   https://user-images.githubusercontent.com/7249484/116806769-c4640a00-ab61-11eb-8d94-6811a22071e4.png
> 
> Eye icon for hiding ALL balances.
> 
> * By default it is unclicked and all balances are presented
> * if an icon is clicked then the icon become strikethrough and ALL amounts in balances and transactions should be hidden
> * if the user clicks strikethrough eye again ALL amounts in balances and transactions should be shown
> 
> 2. moved to [Small view: Assets screen and sorting #178](https://github.com/BeamMW/web-wallet/issues/178)
> 3. moved to [Small view: Asset's detail screen  #179](https://github.com/BeamMW/web-wallet/issues/179)
> 4. moved from [Small view: Asset's info and extended balance #180](https://github.com/BeamMW/web-wallet/issues/180)

moved to https://github.com/BeamMW/web-wallet/issues/178
 1. Main screen 
 Need to add:
 **Show All** button for assets 
- If there are only 3 or fewer assets, hide **Show all** icon
- Beam should be placed on top of assets
https://user-images.githubusercontent.com/7249484/116806769-c4640a00-ab61-11eb-8d94-6811a22071e4.png

**Comment by Sergei-Beam** [comment]
@razoorka let's do here only the next :

Eye icon for hiding ALL balances.

By default it is unclicked and all balances are presented
if an icon is clicked then the icon become strikethrough and ALL amounts in balances and transactions should be hidden
if the user clicks strikethrough eye again ALL amounts in balances and transactions should be shown

**Comment by Sergei-Beam** [comment]
@razoorka looks like we need to store it in local storage or somehow bind to the session because: 
- if I clicked the eye, collapsed and expanded the extension, then it is reset - the balances are made visible

- if I pressed the eye and made the lock wallet, and then unlock - the balances are made visible 
![image](https://user-images.githubusercontent.com/44496108/150835666-0deabd56-b61b-45a3-bbae-c9f2f34f62c0.png)

**Comment by Sergei-Beam** [comment]
checked
