### ISSUE TITLE
Small view: Update design of input fields on send and receive screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/web-wallet#58]
1) Please update input line with the input filed.
![image](https://user-images.githubusercontent.com/47353570/151847677-df65e5d1-5b10-4555-83f3-c370aa47532d.png)
https://zpl.io/254vwMr

2) Opacity 5% if it's non focused field
3) Opacity 10% if it's focused field
4) All the states for input fields are here https://zpl.io/Vk9v1e8

5) Pasted address https://zpl.io/Vq41gEZ
![image](https://user-images.githubusercontent.com/47353570/151848091-4f02d971-a239-4cd7-8543-c72ee6bcfa23.png)

6) Focused on address field https://zpl.io/25mEAAJ
![image](https://user-images.githubusercontent.com/47353570/151848151-20864fbe-d739-4342-99b5-8b0d4b07cd82.png)

7) Focused on comment https://zpl.io/Vxqm6R3
![image](https://user-images.githubusercontent.com/47353570/151848240-95e2097f-89a7-4ad1-b85c-16fd7f882dbd.png)

8) The same for receive screen https://zpl.io/aX78Pgl
![image](https://user-images.githubusercontent.com/47353570/151848342-6d67d1be-1aa0-4dd1-b7ab-f21ee7ddd82a.png)

9) Error https://zpl.io/Z09xOLl
![image](https://user-images.githubusercontent.com/47353570/151848781-0b3d8b66-9a80-445a-89f0-602155d7f3ae.png)

**Comment by kovaletskaterina** [comment]
- When the address field out of focus, the entered address should be reduced as on the design.

![image](https://user-images.githubusercontent.com/83376495/171022931-3dceeec4-61c0-470f-972f-c4adbe28242b.png)

- The error message should be changed from "Invalid wallet address" to "Incorrect address" as on the design.

![image](https://user-images.githubusercontent.com/83376495/171023046-d08dc527-ad16-468c-af9b-bf90db53065f.png)

**Comment by Sergei-Beam** [comment]
checked
