### ISSUE TITLE
Change comment about exchange rate to USD

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/web-wallet#63]
In transaction details change the comment about exchange rate to "USD exchange rate..." (or "BTC/ETH rate" depending on selected secondary currency).

The full text should be:
"(USD exchange rate was not available at the time of transaction)" or
"(USD rate calculated with the exchange rate at the time of transaction)"

Regular tx details: https://zpl.io/bleK1y5
![image](https://user-images.githubusercontent.com/47353570/134491759-105a0f68-256a-4fe8-9feb-35cf6e4afd72.png)

Confidential assets transaction details: https://zpl.io/2Z3RPQ1
![image](https://user-images.githubusercontent.com/47353570/134491493-c0a78951-5cc7-4239-90d4-75c7896177eb.png)

The same for a small view also.

**Comment by gingervik** [comment]
irrelevant
