### ISSUE TITLE
Web apps: logged out wallet

### ISSUE THREAD

**Issue by chapati** [BeamMW/web-wallet#9]
If application is requesting connection but wallet is logged out need to 
1) show connection screen
2) if user approves connection redirect to login/wallet creation. If doesn't approve just stop.
3) if login/creation is successful inject api

**Comment by Sergei-Beam** [comment]
After deleting the wallet via setting and run Dapps connection didn't redirect to login/wallet creation.
![image](https://user-images.githubusercontent.com/44496108/136526249-8dd8d6fe-0c19-4074-a384-a774d4b5854f.png)

**Comment by Sergei-Beam** [comment]
checked
