### ISSUE TITLE
Small view: Restore for Web wallet

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/web-wallet#92]
make a restore according to design when this task will be done https://github.com/BeamMW/beam/issues/1504

extension view: https://zpl.io/VQj6yjx
fullscreen: https://zpl.io/b6zG5ng

**Comment by dariatarakanova** [comment]
1) Add button "restore wallet" that fixed 50 px from bottom https://zpl.io/aM3MD4o
![image](https://user-images.githubusercontent.com/47353570/146437266-bfcf13d9-288f-4b37-8b1d-0a929426c86e.png)


2) Confirmation restore wallet or create new one https://zpl.io/2E9QBkD
![image](https://user-images.githubusercontent.com/47353570/146436753-02356c4c-1c97-4b98-803a-2d07c2f59e22.png)

3) On next screen with buttons add arrow back, so user can get back to login screen https://zpl.io/VKLdPwE
![image](https://user-images.githubusercontent.com/47353570/146436886-80896a75-fe3a-4b63-a33f-86f3587adef2.png)

4) When user click on "restore" show notification https://zpl.io/adw6DKE
![image](https://user-images.githubusercontent.com/47353570/146437423-f55fe98a-2a47-43b8-a17a-8048b1b9d872.png)

5) Next step: user should fills in see phrase https://zpl.io/aBpzdJk
![image](https://user-images.githubusercontent.com/47353570/146437562-86b253c4-e8d6-4b2f-a9b0-8ef39aebc612.png)
- if seed phrase not filled fully - button inactive
-  if seed phrase filled fully - button active https://zpl.io/ammgzdv
![image](https://user-images.githubusercontent.com/47353570/146437957-ef752e53-bea7-4216-ba4f-f00823ae3edc.png)

6) Then create password screen https://zpl.io/25jKjxn
![image](https://user-images.githubusercontent.com/47353570/146438412-305b107d-3e3d-4414-8797-9fbb55a960be.png)

Password flow and states in this task https://github.com/BeamMW/web-wallet/issues/28

7)Restoring wallet screen https://zpl.io/anQ3pPr
![image](https://user-images.githubusercontent.com/47353570/146438838-73b6028d-92f7-4d70-9015-331ba6b88bec.png)

8) Restore failure https://zpl.io/amw35K6
![image](https://user-images.githubusercontent.com/47353570/146439810-990e6c67-b24b-44af-99c0-da38a6bbfc6f.png)
