### ISSUE TITLE
Settings screen: changes for "remove current wallet"

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#94]
![image](https://user-images.githubusercontent.com/44496108/136994888-6cc2132a-704c-4fb3-839b-98a6bf48ac81.png)
1. Change button next to proceed on the pop-up
2. Move "Are you sure you want to remove your wallet?" on a separate line
3. Change proceed button colour to **#f25f5b** according to design
![image](https://user-images.githubusercontent.com/44496108/136995628-9a8cdb17-8bba-41a5-bafb-0a7358f3984b.png)
![image](https://user-images.githubusercontent.com/44496108/136995569-0d36222e-09a1-4516-95ef-0eee6f5fefb4.png)
4. Add a warning message if the user enters the wrong password
![image](https://user-images.githubusercontent.com/44496108/136996157-d571b238-ca95-4c78-bdb1-98e12901acfa.png)

**Comment by kovaletskaterina** [comment]
In point 4 warning message should be hidden:
if user clear the password field;
if user enters another password
![image](https://user-images.githubusercontent.com/83376495/139275853-1aa715f5-7ce7-46c1-82c3-958bb4c37c98.png)

5. When you click on "remove" button without entering a password while remove your current wallet and than enter a password warning message should be hidden.
![image](https://user-images.githubusercontent.com/83376495/139278224-7b70d1cd-bc9c-4709-9e3e-f3f9604e8d1c.png)

**Comment by kovaletskaterina** [comment]
Checked
