### ISSUE TITLE
Add wallet version into wallet settings

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/web-wallet#95]
Need to show current wallet session into wallet setting
![image](https://user-images.githubusercontent.com/44496108/137102585-21fb5858-eaff-44e1-99e2-d130dd431450.png)

**Comment by Sergei-Beam** [comment]
the build version is shortened but must have the full version
![image](https://user-images.githubusercontent.com/44496108/137626369-3fe7eb27-4926-4112-ad5b-c44e6c297215.png)

**Comment by iscander01** [comment]
@anatolse please add full version in get_version api method

**Comment by iscander01** [comment]
version info is shown from manifest.json

**Comment by Sergei-Beam** [comment]
Checked
